// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using br.com.fiap.alert.Data.Contexts;

#nullable disable

namespace br.com.fiap.alert.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("br.com.fiap.alert.Models.AlertModel", b =>
                {
                    b.Property<int>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertId"));

                    b.Property<string>("Author")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Coords")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Message")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TypeAlert")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("AlertId");

                    b.ToTable("TB_ALERT", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
